-- Seed retroactive changelog entries
INSERT INTO public.system_changelog (title, description, category, status, module, released_at) VALUES
('Busca acadêmica multi-fonte', 'Sistema de busca integrada com PubMed, OpenAlex, CrossRef, Semantic Scholar, EuropePMC e CORE. Deduplicação por DOI e enriquecimento de citações.', 'feature', 'released', 'search', '2025-01-15'),
('Biblioteca pessoal', 'Gerenciamento de papers salvos com filtros, tags e exportação bibliográfica em múltiplos formatos (APA, Vancouver, ABNT, BibTeX).', 'feature', 'released', 'library', '2025-01-20'),
('Extração de dados com IA', 'Extração automatizada de dados de artigos científicos usando IA, com colunas customizáveis e cache inteligente.', 'feature', 'released', 'extraction', '2025-02-01'),
('Classificação de citações', 'Classificação automática de citações como supporting, contrasting ou mentioning usando IA.', 'feature', 'released', 'search', '2025-02-10'),
('Geração de relatórios', 'Geração de relatórios científicos com síntese por IA, exportação em múltiplos formatos.', 'feature', 'released', 'reports', '2025-02-15'),
('Verificação de referências', 'Verificação automatizada de referências bibliográficas com detecção de retrações e erros.', 'feature', 'released', 'reference-check', '2025-02-20'),
('Ilustrações científicas com IA', 'Geração de ilustrações científicas usando IA generativa com estilos customizáveis e editor de anotações.', 'feature', 'released', 'illustrations', '2025-03-01'),
('DataMind - Análise de dados', 'Módulo de análise de dados com chat por linguagem natural, execução de código Python/R, upload de arquivos e visualizações interativas.', 'feature', 'released', 'datamind', '2025-03-05'),
('DataMind - Dashboards', 'Criação de dashboards interativos com widgets pinados de análises, compartilhamento público via link.', 'feature', 'released', 'datamind', '2025-03-10'),
('DataMind - Pipelines reutilizáveis', 'Salvamento e reutilização de sequências de análise como templates de pipeline.', 'feature', 'released', 'datamind', '2025-03-12'),
('DataMind - Versioning e checkpoints', 'Sistema de checkpoints e branches para versionamento de análises.', 'feature', 'released', 'datamind', '2025-03-13'),
('Mapa de conhecimento', 'Grafo de citações interativo com force-directed layout para explorar relações entre papers.', 'feature', 'released', 'knowledge-graph', '2025-03-15'),
('Workspaces colaborativos', 'Criação de workspaces para colaboração entre pesquisadores com controle de acesso por papéis.', 'feature', 'released', 'workspaces', '2025-03-18'),
('Assistente de escrita científica', 'IA para auxílio na redação científica com sugestões de melhoria, paráfrase e tradução.', 'feature', 'released', 'writing', '2025-03-20'),
('Meta-análise', 'Módulo de meta-análise com forest plots, funnel plots e cálculos estatísticos automatizados.', 'feature', 'released', 'meta-analysis', '2025-03-22'),
('Alertas de literatura', 'Monitoramento automatizado de novas publicações com alertas por e-mail configuráveis.', 'feature', 'released', 'alerts', '2025-03-25'),
('Avaliação de risco de viés', 'Ferramenta de avaliação de risco de viés (RoB) com múltiplas ferramentas padronizadas.', 'feature', 'released', 'risk-of-bias', '2025-04-01'),
('Formulários de pesquisa (eCRF)', 'Construtor de formulários com múltiplos tipos de pergunta, lógica condicional, consentimento informado (TCLE) e distribuição.', 'feature', 'released', 'surveys', '2025-04-10'),
('Revisão sistemática', 'Módulo completo para revisão sistemática com etapas guiadas: pergunta PICO, busca, screening, extração e relatório.', 'feature', 'released', 'systematic-review', '2025-04-15'),
('DataSUS/SINAN - Dados reais', 'Integração com InfoDengue, IBGE SIDRA, OpenDataSUS e IBGE Agregados para consultas com dados epidemiológicos reais.', 'integration', 'released', 'datasus', '2025-05-01'),
('Alertas epidemiológicos', 'Sistema de detecção de surtos com alertas automáticos baseados em análise estatística de séries temporais.', 'feature', 'released', 'datasus', '2025-05-10'),
('Boletins epidemiológicos automáticos', 'Geração automática de boletins epidemiológicos em PDF com análise de tendências e mapas.', 'feature', 'released', 'datasus', '2025-05-12'),
('Mapas coropléticos interativos', 'Mapa do Brasil SVG interativo com indicadores por UF e animação temporal.', 'feature', 'released', 'datasus', '2025-05-14'),
('Integridade de dados (hashing)', 'Sistema de integridade criptográfica com SHA-256 para respostas de formulários, auditoria de alterações e verificação de inviolabilidade.', 'feature', 'released', 'surveys', '2025-05-20'),
('Oracle Agent', 'Assistente IA contextual acessível de qualquer página para dúvidas sobre o sistema.', 'feature', 'released', 'global', '2025-04-20'),
('Painel administrativo', 'Interface administrativa com gestão de usuários, aprovações, chaves de API e analytics de uso.', 'feature', 'released', 'admin', '2025-02-25'),
('Sistema de autenticação e RBAC', 'Autenticação com Supabase Auth, aprovação de novos usuários, controle de acesso baseado em papéis (admin/user).', 'feature', 'released', 'auth', '2025-01-10'),
('Planos e assinatura (Stripe)', 'Integração com Stripe para planos Free/Pro/Enterprise com controle de uso e limites por funcionalidade.', 'integration', 'released', 'billing', '2025-03-01');